services:
  product-service:
    build: ../product-service
    command: uv run uvicorn src.main:app --host 0.0.0.0 --port 8001 --reload
    volumes:
      # Mount the local product-service code for development
      - ../product-service:/app   # Mount source code
      - /app/.venv                # Persist virtual environment
    env_file:
      - .env
    environment:
      - DATABASE_URL=${PRODUCT_SERVICE_DATABASE_URL}
      - AUTH_GRPC_CLIENT_HOST=${AUTH_GRPC_CLIENT_HOST}
      - AUTH_GRPC_CLIENT_PORT=${AUTH_GRPC_CLIENT_PORT}
      - RABBITMQ_URL=${RABBITMQ_URL}
    depends_on:
      - product-db
      - rabbitmq
    networks:
      - backend_network

  auth-service:
    build: ../auth-service
    command: uv run uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      # Mount the local auth-service code for development
      - ../auth-service:/app   # Mount source code
      - /app/.venv                # Persist virtual environment
    env_file:
      - .env
    environment:
      - DATABASE_URL=${AUTH_SERVICE_DATABASE_URL}
    depends_on:
      - auth-db
      - rabbitmq
    networks:
      - backend_network

  auth-db:
    image: postgres:latest
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${AUTH_SERVICE_POSTGRES_USER}
      - POSTGRES_PASSWORD=${AUTH_SERVICE_POSTGRES_PASSWORD}
      - POSTGRES_DB=${AUTH_SERVICE_POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - auth-db-data:/var/lib/postgresql
    networks:
      - backend_network

  product-db:
    image: postgres:latest
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${PRODUCT_SERVICE_POSTGRES_USER}
      - POSTGRES_PASSWORD=${PRODUCT_SERVICE_POSTGRES_PASSWORD}
      - POSTGRES_DB=${PRODUCT_SERVICE_POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - product-db-data:/var/lib/postgresql
    networks:
      - backend_network

  api-gateway:
    build: ./gateway
    ports:
      - "80:80"
    depends_on:
      - product-service
      - auth-service
    networks:
      - gateway_network
      - backend_network
    restart: always

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/mnesia/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq/
    networks:
      - backend_network
    restart: always

volumes:
  product-db-data:
    driver: local
  auth-db-data:
    driver: local

networks:
  gateway_network:  # Nginx gateway network
  backend_network:  # Microservices network
