services:
  db:
    image: postgres:18
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${LOCAL_POSTGRES_USER}
      - POSTGRES_PASSWORD=${LOCAL_POSTGRES_PASSWORD}
      - LOCAL_POSTGRES_DATABASES=${LOCAL_POSTGRES_DATABASES}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432" # Expose PostgreSQL port
    volumes:
      - db-data:/var/lib/postgresql
      - ./scripts/create-dbs.sh:/docker-entrypoint-initdb.d/create-dbs.sh
    networks:
      - local_infra_network
  
  rabbitmq:
    image: rabbitmq:3-management
    env_file:
      - .env
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"  # RabbitMQ main port
      - "15672:15672" # RabbitMQ management UI
    networks:
      - local_infra_network

volumes:
  db-data:
    driver: local

networks:
  local_infra_network:
    driver: bridge
